Ext.define(AppConfig.appName + '.model.Employer', {
    extend: 'Ext.data.Model',
    xtype: 'employer',
    idProperty: 'Display',
    fields: [
        { name: 'Seq' },
        { name: 'EMID', type: 'string' },
        { name: 'EMIDFlg', type: 'string' },
        { name: 'EMTName', type: 'string' },
        { name: 'EMName', type: 'string' },
        { name: 'EMMName', type: 'string' },
        { name: 'EMSName', type: 'string' },
        { name: 'EMHouse', type: 'string' },
        { name: 'EMMoo', type: 'string' },
        { name: 'EMBuilding', type: 'string' },
        { name: 'EMSoi', type: 'string' },
        { name: 'EMRoad', type: 'string' },
        { name: 'EMVillange', type: 'string' },
        { name: 'EMTamb', type: 'string' },
        { name: 'EMTambName', type: 'string' },
        { name: 'EMAmp', type: 'string' },
        { name: 'EMAmpName', type: 'string' },
        { name: 'EMProv', type: 'string' },
        { name: 'EMProvName', type: 'string' },
        { name: 'EMPost', type: 'string' },
        { name: 'EMTel', type: 'string' },
        { name: 'EMFax', type: 'string' },
        { name: 'EMMobile', type: 'string' },
        { name: 'EMVersionNO', type: 'string' },
        { name: 'Display', type: 'string' },
        { name: 'FullName', type: 'string' },
        { name: 'EWLoc', type: 'string' }
    ]
});